openapi: 3.0.0
info:
  title: API Artistas
  description: API para gerenciar informações de artistas
  version: 1.0.0

servers:
  - url: "https://localhost:3000"

tags:
  - name: User
    description: Operações relacionadas a usuários

  - name: Artistas
    description: Operações relacionadas a artistas

  - name: Songs
    description: Operações relacionadas a músicas

  - name: Albums
    description: Operações relacionadas a álbuns

  - name: Admin
    description: Operações administrativas

paths:
  # rota
  /user/register:
    # metodo
    post:
      # titulo
      summary: "Cadastro de usuário"
      # descricao
      description: "Cria um novo usuário no sistema"
      tags:
        - User

        # corpo da requisição
      requestBody:
        # tipo de conteudo
        content:
          application/json:
            # esquema de dados
            schema:
              $ref: "#/components/schemas/UserRegister"
              # exemplo de dados
            examples:
              User:
                summary: "Exemplo de usuário"
                value:
                  name: "João Silva"
                  email: "joao.silva@example.com"
                  password: "senha123"
      # resposta
      responses:
        "400":
          description: "Erro ao criar usuário"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"

                example:
                  message: "Erro ao criar usuário"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
        "201":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegister"

  /user/all:
    get:
      summary: "Listar todos os usuários"
      description: "Retorna uma lista de todos os usuários cadastrados"
      tags:
        - User

      # get não usa requestBody, mas sim parâmetros de consulta
      responses:
        "200":
          description: "Lista de usuários"
          content:
           application/json:
            schema:
            # é do tipo array pois me retorna uma lista de usuários
              type: array
              items:
                $ref: "#/components/schemas/UserRegister"

            example:
              User:

                value: 
                  - id: 1
                    name: "João Silva"
                    email: "joao.silva@example.com"
                    password: "hashedPassword"

                  - id: 2
                    name: "Roberto Souza"
                    email: "roberto.souza@example.com"
                    password: "hashedPassword"

                  - id: 3
                    name: "Maria Oliveira"
                    email: "maria.oliveira@example.com"
                    password: "hashedPassword"
        '500':
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"

                example:
                  message: "Erro interno do servidor"             

  /user/login:
    post:
      summary: "Login de usuário"
      description: "Realiza o login de um usuário no sistema"
      tags:
        - User
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
              examples:
                User:
                  summary: "Exemplo de usuário"
                  value:
                    email: "joao.silva@example.com"
                    password: "hashedPassword"

      responses:
        "404":
          description: "Usuário não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Usuário não encontrado"


        "400":
          description: "Erro ao realizar login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Email ou senha inválidos"

        "200":
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "Token de autenticação do usuário"

              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
  /user/delete/{id}:
    delete:
      summary: "Deletar usuário"
      tags:
        - User
      description: "Deleta um usuário do sistema"
      parameters:
        - name: id
          in: path
          description: "ID do usuário a ser deletado"
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Usuário deletado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Deletado com sucesso"
                example:
                  message: "Usuário deletado com sucesso"
        "404":
          description: "Usuário não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Usuário não encontrado"
                example:
                  message: "Usuário não encontrado"
          
        "400":
          description: "ID inválido"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "ID inválido"
                example:
                  message: "ID inválido"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /admin/register:
    post:
      tags:
        - Admin
      summary: "Cadastro de administrador"
      description: "Cria um novo administrador no sistema"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        "200":
          description: "Administrador criado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegister"
              examples:
                Admin:
                  summary: "Exemplo de administrador criado"
                  value:
                    name: "Admin"
                    email: "admin@example.com"
                    password: "admin123"

        "400":
          description: "Email inválido ou senha muito curta"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Email inválido ou senha muito curta"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"                    

# aqui eu crio componentes que serão reutilizados
components:
  schemas:
    UserRegister:
      type: object
      properties:
        email:
          type: string
          description: "Email do usuário"

        password:
          type: string
          description: "Senha do usuário"
        name:
          type: string
          description: "Nome do usuário"

    UserLogin:
      type: object
      properties:
        email:
          type: string
          description: "Email do usuário"

        password:
          type: string
          description: "Senha do usuário"
  # aqui eu defino os esquemas de segurança
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT

    